export const projects = [
  {
    id: 14,
    title: "LearnLingo",
    description:
      "A web application for an online language learning platform. Built with React, Firebase (Auth & Realtime Database).",
    role: "Front-End Developer",
    tech: ["React", "Firebase", "CSS"],
    image: "/images/learnlingo.png",
    demo: "https://learnlingo.chasov-dev.com/",
    code: "https://github.com/chasov-artem/english",
    logoImage: "/images/learnlingo1.png",
  },
  {
    id: 13,
    title: "Billiard-servis",
    description:
      "This is my first commercial web catalog project for billiards products. It features CSV product import, an admin panel for catalog management, and a responsive, modern UI.",
    role: "Front-End Developer",
    tech: ["React", "Firebase", "CSS"],
    image: "/images/billiard.png",
    demo: "https://www.billiard-servis.com/",
    code: "https://github.com/chasov-artem/billirds-catalog",
    logoImage: "/images/billiard1.png",
  },
  {
    id: 12,
    title: "Organic",
    description:
      "Organic is a responsive eco‑products landing page with a clean, modern design and adaptive layout.",
    role: "Front-End Developer",
    tech: ["JS", "HTML", "CSS"],
    image: "/images/organic.png",
    demo: "https://organic.chasov-dev.com/",
    code: "https://github.com/chasov-artem/organic-repo",
    logoImage: "/images/organic1.png",
  },
  {
    id: 11,
    title: "Flights App",
    description:
      "Flights is a responsive web application for searching and browsing flight options in real time. It features a clean, modern UI built with React and modular CSS, focusing on speed and user-friendly interactions. The project demonstrates API data fetching, dynamic rendering of flight results, and smooth navigation for both desktop and mobile users.",
    role: "Front-End Developer",
    tech: ["React", "CSS"],
    image: "/images/flights.png",
    demo: "https://flights.chasov-dev.com/",
    code: "https://github.com/chasov-artem/flights",
    logoImage: "/images/flights1.png",
  },
  {
    id: 10,
    title: "Posts App2",
    description:
      "Posts App2 is a Flutter Web app with full CRUD for posts, using Provider for state management and JSONPlaceholder as a REST API.",
    role: "Front-End Developer",
    tech: ["Flutter"],
    image: "/images/posts2-1.png",
    demo: "https://postsapp2.chasov-dev.com/",
    code: "https://github.com/chasov-artem/DOiT-2",
    logoImage: "/images/posts2-2.png",
  },
  {
    id: 9,
    title: "Posts App",
    description:
      "A responsive blog demo built with Next.js, Material-UI, and Redux. Features post browsing, creation, deletion, comments, search, and theme switching. Uses JSONPlaceholder API for mock data.",
    role: "Front-End Developer",
    tech: ["Next", "Redux", "Material-UI"],
    image: "/images/posts-1.png",
    demo: "https://postsapp.chasov-dev.com/",
    code: "https://github.com/chasov-artem/DOiT",
    logoImage: "/images/posts-2.png",
  },
  {
    id: 8,
    title: "CRM",
    description:
      "This is a learning CRM project built with Next.js 14, React Query, and mock APIs. It demonstrates dynamic routing, server-side rendering, and modern UI features like modal forms and real-time data updates.",
    role: "Front-End Developer",
    tech: ["Next", "React Query"],
    image: "/images/crm1.png",
    demo: "https://crm.chasov-dev.com/dashboard",
    code: "https://github.com/chasov-artem/crm",
    logoImage: "/images/crm2.png",
  },
  {
    id: 7,
    title: "TravelTrucks",
    description:
      "Travel Trucks is a campervan rental web application that allows users to browse available campervans, filter them by various parameters, view detailed information, and make reservations. An individual project.",
    role: "Front-End Developer",
    tech: ["React", "Redux"],
    image: "/images/traveltrucks.png",
    demo: "https://traveltrucks.chasov-dev.com/",
    code: "https://github.com/chasov-artem/TravelTrucks",
    logoImage: "/images/camper.png",
  },
  {
    id: 6,
    title: "SparkArt",
    description:
      "This is a landing page for a game. A page with a responsive design, a burger menu and a swiper for mobile devices. Developed all sections starting from the FAQ section and below. Team project(two developers and designer)",
    role: "Front-End Developer",
    tech: ["HTML", "CSS", "JS"],
    image: "/images/sparkart.png",
    demo: "https://dmytrok-goit.github.io/stp-7973//",
    code: "https://github.com/DmytroK-goit/stp-7973",
    logoImage: "/images/art.png",
  },
  {
    id: 5,
    title: "AquaTrack",
    description:
      "This is an app for controlling water consumption. With a backend created for the needs of the application, with login, responsive design, and water controlling features. I was responsible for the user panel section.",
    role: "Scrum Master and Front-End Developer",
    tech: ["React", "Redux", "Node"],
    image: "/images/aquatrack.png",
    demo: "https://aqua-track-group-01.vercel.app/",
    code: "https://github.com/DmytroK-goit/AquaTrack-group-01",
    logoImage: "/images/aqua.png",
  },
  {
    id: 4,
    title: "Phonebook",
    description:
      "A contact management app with secure login, real-time notifications, and a responsive, animated interface. I developed contact CRUD functionality, implemented JWT authorization, and designed the interactive home page. An individual project.",
    role: "Front-End Developer",
    tech: ["React", "Redux", "JWT"],
    image: "/images/phonebook.png",
    demo: "https://phonebook.chasov-dev.com",
    code: "https://github.com/chasov-artem/goit-react-hw-08",
    logoImage: "/images/phone.png",
  },
  {
    id: 3,
    title: "Portfolio",
    description:
      "A developer portfolio website with animations, modal windows, and a swiper for smooth navigation. I was in charge of creating the covers section. Team project.",
    role: "Scrum Master and Front-End Developer",
    tech: ["HTML", "CSS", "JS"],
    image: "/images/portfolio.png",
    demo: "https://dmytrok-goit.github.io/project-js-group02/",
    code: "https://github.com/DmytroK-goit/project-js-group02",
    logoImage: "/images/port.png",
  },
  {
    id: 2,
    title: "Watchcharm",
    description:
      "A website for a wristwatch sales company, featuring a responsive design. I was responsible for developing the sales section. Team project.",
    role: "Scrum Master and Front-End Developer",
    tech: ["HTML", "CSS"],
    image: "/images/watchcharm2.png",
    demo: "https://denismayboroda.github.io/project-Do-your-first-step/",
    code: "https://github.com/DenisMayboroda/project-Do-your-first-step",
    logoImage: "/images/watch.png",
  },
  {
    id: 1,
    title: "WebStudio",
    description:
      "A website for the WebStudio company featuring responsive design, animation effects, and modal windows. An individual project.",
    role: "Front-End Developer",
    tech: ["HTML", "CSS"],
    image: "/images/webstudio.png",
    demo: "https://webstudio.chasov-dev.com",
    code: "https://github.com/chasov-artem/goit-markup-hw-06/",
    logoImage: "/images/web.png",
  },
];
