export const projects = [
  {
    id: 7,
    title: "TravelTrucks",
    description:
      "Travel Trucks is a campervan rental web application that allows users to browse available campervans, filter them by various parameters, view detailed information, and make reservations. An individual project.",
    role: "Front-End Developer",
    tech: ["React", "Redux"],
    image: "/images/traveltrucks.png",
    demo: "https://travel-trucks-hx3g.vercel.app/",
    code: "https://github.com/chasov-artem/TravelTrucks",
    logoImage: "/images/camper.png",
  },
  {
    id: 6,
    title: "SparkArt",
    description:
      "This is a landing page for a game. A page with a responsive design, a burger menu and a swiper for mobile devices. Developed all sections starting from the FAQ section and below. Team project(two developers and designer)",
    role: "Front-End Developer",
    tech: ["HTML", "CSS", "JS"],
    image: "/images/sparkart.png",
    demo: "https://dmytrok-goit.github.io/stp-7973//",
    code: "https://github.com/DmytroK-goit/stp-7973",
    logoImage: "/images/art.png",
  },
  {
    id: 5,
    title: "AquaTrack",
    description:
      "This is an application for controlling water consumption. With a backend created for the needs of the application, with login, responsive design, and features for controlling water consumption. I was responsible for developing the user panel section. Team project.",
    role: "Scrum Master and Front-End Developer",
    tech: ["React", "Redux", "Node"],
    image: "/images/aquatrack.png",
    demo: "https://aqua-track-group-01.vercel.app/",
    code: "https://github.com/DmytroK-goit/AquaTrack-group-01",
    logoImage: "/images/aqua.png",
  },
  {
    id: 4,
    title: "Phonebook",
    description:
      "A contact management app with secure login, real-time notifications, and a responsive, animated interface. I developed contact CRUD functionality, implemented JWT authorization, and designed the interactive home page. An individual project.",
    role: "Front-End Developer",
    tech: ["React", "Redux", "JWT"],
    image: "/images/phonebook.png",
    demo: "https://goit-react-hw-08-pink-one.vercel.app/",
    code: "https://github.com/chasov-artem/goit-react-hw-08",
    logoImage: "/images/phone.png",
  },
  {
    id: 3,
    title: "Portfolio",
    description:
      "A developer portfolio website with animations, modal windows, and a swiper for smooth navigation. I was in charge of creating the covers section. Team project.",
    role: "Scrum Master and Front-End Developer",
    tech: ["HTML", "CSS", "JS"],
    image: "/images/portfolio.png",
    demo: "https://dmytrok-goit.github.io/project-js-group02/",
    code: "https://github.com/DmytroK-goit/project-js-group02",
    logoImage: "/images/port.png",
  },
  {
    id: 2,
    title: "Watchcharm",
    description:
      "A website for a wristwatch sales company, featuring a responsive design. I was responsible for developing the sales section. Team project.",
    role: "Scrum Master and Front-End Developer",
    tech: ["HTML", "CSS"],
    image: "/images/watchcharm2.png",
    demo: "https://denismayboroda.github.io/project-Do-your-first-step/",
    code: "https://github.com/DenisMayboroda/project-Do-your-first-step",
    logoImage: "/images/watch.png",
  },
  {
    id: 1,
    title: "WebStudio",
    description:
      "A website for the WebStudio company featuring responsive design, animation effects, and modal windows. An individual project.",
    role: "Front-End Developer",
    tech: ["HTML", "CSS"],
    image: "/images/webstudio.png",
    demo: "https://chasov-artem.github.io/goit-markup-hw-06/",
    code: "https://github.com/chasov-artem/goit-markup-hw-06/",
    logoImage: "/images/web.png",
  },
];
